"""The built-in guide to the texture analysis: short text, a few formulas and pre-rendered demonstrations.

Opened from the Help menu and from the texture window. The demonstrations live in
``assets/guide`` (regenerated by ``scripts/make_guide_animations.py``): two GIF animations played with
:class:`~PySide6.QtGui.QMovie` and one still image. Nothing here is interactive beyond scrolling.
"""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtGui import QMovie, QPixmap
from PySide6.QtWidgets import QFrame, QLabel, QMainWindow, QScrollArea, QVBoxLayout, QWidget

from .theme import COLORS
from .widgets import guard_wheel

ASSETS = Path(__file__).resolve().parent / "assets" / "guide"
MEDIA = {"region": "region_window.gif", "rve": "rve_sweep.gif", "subset": "subset.png"}
PAGE_WIDTH = 760
REGION_COLOR = "#f97316"

__all__ = ["GuideWindow"]


class GuideWindow(QMainWindow):
    """Why a region, what the autocorrelation measures, why the RVE, how the subset follows."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setWindowFlag(Qt.WindowType.Window, True)
        self.resize(PAGE_WIDTH + 80, 860)
        self.movies: list[QMovie] = []
        self.pixmaps: list[QPixmap] = []
        self._text: dict[str, QLabel] = {}

        page = QWidget()
        page.setMaximumWidth(PAGE_WIDTH)
        layout = QVBoxLayout(page)
        layout.setContentsMargins(24, 20, 24, 28)
        layout.setSpacing(10)
        self._text["title"] = self._label(layout, size=20, bold=True)
        self._text["intro"] = self._label(layout)
        self._add_section(layout, "acf", media=None, formula=True)
        self._add_section(layout, "region", media="region")
        self._add_section(layout, "rve", media="rve")
        self._add_section(layout, "subset", media="subset", formula=True)
        layout.addStretch(1)

        outer = QWidget()
        outer_layout = QVBoxLayout(outer)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.addWidget(page, 0, Qt.AlignmentFlag.AlignHCenter)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(outer)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setCentralWidget(scroll)
        guard_wheel(page)
        self.retranslate_ui()

    # ------------------------------------------------------------------ building blocks
    @staticmethod
    def _label(layout, size: int = 12, bold: bool = False, color: str = COLORS.TEXT_PRIMARY) -> QLabel:
        lab = QLabel()
        lab.setWordWrap(True)
        lab.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        weight = "bold" if bold else "normal"
        lab.setStyleSheet(f"font-size: {size}px; font-weight: {weight}; color: {color};")
        layout.addWidget(lab)
        return lab

    def _add_section(self, layout, key: str, media: str | None, formula: bool = False) -> None:
        rule = QFrame()
        rule.setFrameShape(QFrame.Shape.HLine)
        rule.setStyleSheet(f"color: {COLORS.BORDER};")
        layout.addSpacing(8)
        layout.addWidget(rule)
        self._text[f"{key}_head"] = self._label(layout, size=15, bold=True)
        self._text[f"{key}_body"] = self._label(layout)
        if formula:
            box = QLabel()
            box.setAlignment(Qt.AlignmentFlag.AlignCenter)
            box.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
            box.setStyleSheet(
                f"font-size: 15px; color: {COLORS.TEXT_PRIMARY}; background: {COLORS.BG_PANEL};"
                f" border: 1px solid {COLORS.BORDER}; border-radius: 6px; padding: 10px 14px;"
            )
            layout.addWidget(box)
            self._text[f"{key}_formula"] = box
        if media is not None:
            self._add_media(layout, media)
            self._text[f"{key}_caption"] = self._label(layout, size=11, color=COLORS.TEXT_SECONDARY)

    def _add_media(self, layout, key: str) -> None:
        path = ASSETS / MEDIA[key]
        holder = QLabel()
        holder.setAlignment(Qt.AlignmentFlag.AlignCenter)
        holder.setStyleSheet(f"background: {COLORS.BG_CANVAS}; border: 1px solid {COLORS.BORDER}; border-radius: 6px;")
        if path.suffix == ".gif":
            movie = QMovie(str(path))
            movie.setCacheMode(QMovie.CacheMode.CacheAll)
            if movie.isValid():
                holder.setMovie(movie)
                self.movies.append(movie)
            else:
                holder.setText(f"({path.name} missing)")
        else:
            pix = QPixmap(str(path))
            if not pix.isNull():
                holder.setPixmap(pix)
                self.pixmaps.append(pix)
            else:
                holder.setText(f"({path.name} missing)")
        layout.addWidget(holder, 0, Qt.AlignmentFlag.AlignHCenter)

    # ------------------------------------------------------------------ playback follows visibility
    def showEvent(self, event) -> None:  # noqa: N802
        super().showEvent(event)
        for m in self.movies:
            m.start()

    def hideEvent(self, event) -> None:  # noqa: N802
        for m in self.movies:
            m.stop()
        super().hideEvent(event)

    # ------------------------------------------------------------------ text
    def retranslate_ui(self) -> None:
        self.setWindowTitle(self.tr("Texture analysis guide"))
        t = self._text
        t["title"].setText(self.tr("Texture analysis: how it works"))
        t["intro"].setText(
            self.tr(
                "DVC follows small subsets of the volume from one scan to the next. A subset can only be followed when "
                "it holds enough texture: several speckles or grains, not one flat patch. The texture analysis measures "
                "how far the grey values stay correlated and turns that distance into a subset size."
            )
        )
        t["acf_head"].setText(self.tr("Autocorrelation"))
        t["acf_body"].setText(
            self.tr(
                "Take a window of the volume and a copy of it moved by a shift h. The autocorrelation ρ(h) is the "
                "similarity of the two: 1 when h = 0, falling towards 0 once the shift exceeds the size of the speckles. "
                "The correlation length L is the shift at which ρ has dropped to 1/e; the 0.1 and 0.01 lengths mark where "
                "the texture has become independent."
            )
        )
        t["acf_formula"].setText(
            "g(<b>x</b>) = f(<b>x</b>) − mean(f)"
            "<br>ρ(<b>h</b>) = mean[ g(<b>x</b>) · g(<b>x</b> + <b>h</b>) ] / mean[ g(<b>x</b>)<sup>2</sup> ]"
            "<br><span style='color:#94a3b8; font-size:12px;'>f: grey value, mean over the region; ρ(L) = 1/e ≈ 0.37</span>"
        )
        t["region_head"].setText(self.tr("Step 1: the region"))
        t["region_body"].setText(
            self.tr(
                "The window only moves inside the region, so the region fixes the largest shift that can be measured: "
                "(region − window) / 2 on each axis. Choose a region filled with the texture you will track. It is not "
                "the DVC region of interest: the two never affect each other."
            )
        )
        t["region_caption"].setText(
            self.tr(
                "One analysis: the copy (cyan) of the window (white) slides inside the region (orange) while ρ(h) is "
                "traced; the region edge stops it."
            )
        )
        t["rve_head"].setText(self.tr("Step 2: the representative volume element (RVE)"))
        t["rve_body"].setText(
            self.tr(
                "A small window gives a noisy length: it sees only a few speckles. The representative volume element is "
                "the window size from which the length no longer changes. Windows of growing size, all centred in the "
                "region, are analysed with the same shifts; the first size of the stable run becomes the window of step 3."
            )
        )
        t["rve_caption"].setText(
            self.tr("Windows of growing size in the same region; the 1/e length settles once the window is large enough.")
        )
        t["subset_head"].setText(self.tr("Step 3: from the length to the subset"))
        t["subset_body"].setText(
            self.tr(
                "A subset must span several correlation lengths on every axis, so it always holds enough texture: the "
                "suggestion is 2.5 times the 1/e length per axis, rounded to an odd number of voxels, with a step of half "
                "the subset. Apply writes both into the DVC parameters."
            )
        )
        t["subset_formula"].setText("subset ≈ 2.5 · L(1/e)   step ≈ subset / 2")
        t["subset_caption"].setText(
            self.tr("The 1/e length on the texture, the subset it suggests and the step to the next subset.")
        )
