"""The built-in guide to the texture analysis: short text, a few formulas and pre-rendered demonstrations.

Opened from the Help menu and from the texture window. The demonstrations live in
``assets/guide`` (regenerated by ``scripts/make_guide_animations.py``): two GIF animations played with
:class:`~PySide6.QtGui.QMovie` and one still image. Nothing here is interactive beyond scrolling.
"""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import Qt
from PySide6.QtGui import QMovie, QPixmap
from PySide6.QtWidgets import QFrame, QLabel, QMainWindow, QScrollArea, QVBoxLayout, QWidget

from .theme import COLORS
from .widgets import guard_wheel

ASSETS = Path(__file__).resolve().parent / "assets" / "guide"
MEDIA = {"acf": "overlap_correction.gif", "rve": "rve_sweep.gif", "subset": "subset.png"}
PAGE_WIDTH = 760
REGION_COLOR = "#f97316"

__all__ = ["GuideWindow"]


class GuideWindow(QMainWindow):
    """What the autocorrelation measures, why the overlap correction, why the RVE, how the subset follows."""

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setWindowFlag(Qt.WindowType.Window, True)
        self.resize(PAGE_WIDTH + 80, 860)
        self.movies: list[QMovie] = []
        self.pixmaps: list[QPixmap] = []
        self._text: dict[str, QLabel] = {}

        page = QWidget()
        page.setMaximumWidth(PAGE_WIDTH)
        layout = QVBoxLayout(page)
        layout.setContentsMargins(24, 20, 24, 28)
        layout.setSpacing(10)
        self._text["title"] = self._label(layout, size=20, bold=True)
        self._text["intro"] = self._label(layout)
        self._add_section(layout, "acf", media="acf", formula=True)
        self._add_section(layout, "region", media=None)
        self._add_section(layout, "rve", media="rve")
        self._add_section(layout, "subset", media="subset", formula=True)
        layout.addStretch(1)

        outer = QWidget()
        outer_layout = QVBoxLayout(outer)
        outer_layout.setContentsMargins(0, 0, 0, 0)
        outer_layout.addWidget(page, 0, Qt.AlignmentFlag.AlignHCenter)
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(outer)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setCentralWidget(scroll)
        guard_wheel(page)
        self.retranslate_ui()

    # ------------------------------------------------------------------ building blocks
    @staticmethod
    def _label(layout, size: int = 12, bold: bool = False, color: str = COLORS.TEXT_PRIMARY) -> QLabel:
        lab = QLabel()
        lab.setWordWrap(True)
        lab.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
        weight = "bold" if bold else "normal"
        lab.setStyleSheet(f"font-size: {size}px; font-weight: {weight}; color: {color};")
        layout.addWidget(lab)
        return lab

    def _add_section(self, layout, key: str, media: str | None, formula: bool = False) -> None:
        rule = QFrame()
        rule.setFrameShape(QFrame.Shape.HLine)
        rule.setStyleSheet(f"color: {COLORS.BORDER};")
        layout.addSpacing(8)
        layout.addWidget(rule)
        self._text[f"{key}_head"] = self._label(layout, size=15, bold=True)
        self._text[f"{key}_body"] = self._label(layout)
        if formula:
            box = QLabel()
            box.setAlignment(Qt.AlignmentFlag.AlignCenter)
            box.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByMouse)
            box.setStyleSheet(
                f"font-size: 15px; color: {COLORS.TEXT_PRIMARY}; background: {COLORS.BG_PANEL};"
                f" border: 1px solid {COLORS.BORDER}; border-radius: 6px; padding: 10px 14px;"
            )
            layout.addWidget(box)
            self._text[f"{key}_formula"] = box
        if media is not None:
            self._add_media(layout, media)
            self._text[f"{key}_caption"] = self._label(layout, size=11, color=COLORS.TEXT_SECONDARY)

    def _add_media(self, layout, key: str) -> None:
        path = ASSETS / MEDIA[key]
        holder = QLabel()
        holder.setAlignment(Qt.AlignmentFlag.AlignCenter)
        holder.setStyleSheet(f"background: {COLORS.BG_CANVAS}; border: 1px solid {COLORS.BORDER}; border-radius: 6px;")
        if path.suffix == ".gif":
            movie = QMovie(str(path))
            movie.setCacheMode(QMovie.CacheMode.CacheAll)
            if movie.isValid():
                holder.setMovie(movie)
                self.movies.append(movie)
            else:
                holder.setText(f"({path.name} missing)")
        else:
            pix = QPixmap(str(path))
            if not pix.isNull():
                holder.setPixmap(pix)
                self.pixmaps.append(pix)
            else:
                holder.setText(f"({path.name} missing)")
        layout.addWidget(holder, 0, Qt.AlignmentFlag.AlignHCenter)

    # ------------------------------------------------------------------ playback follows visibility
    def showEvent(self, event) -> None:  # noqa: N802
        super().showEvent(event)
        for m in self.movies:
            m.start()

    def hideEvent(self, event) -> None:  # noqa: N802
        for m in self.movies:
            m.stop()
        super().hideEvent(event)

    # ------------------------------------------------------------------ text
    def retranslate_ui(self) -> None:
        self.setWindowTitle(self.tr("Texture analysis guide"))
        t = self._text
        t["title"].setText(self.tr("Texture analysis: how it works"))
        t["intro"].setText(
            self.tr(
                "DVC follows small subsets of the volume from one scan to the next. A subset can only be followed when "
                "it holds enough texture: several speckles or grains, not one flat patch. The texture analysis measures "
                "how far the grey values stay correlated and turns that distance into a subset size."
            )
        )
        t["acf_head"].setText(self.tr("Autocorrelation, and the correction it needs"))
        t["acf_body"].setText(
            self.tr(
                "Take a cube of the volume and a copy of it moved by a lag h. The autocorrelation ρ(h) is the similarity "
                "of the two: 1 when h = 0, falling towards 0 once the lag exceeds the size of the speckles. The "
                "correlation length L is the lag at which ρ has dropped to 1/e; the 0.1 and 0.01 lengths mark where the "
                "texture has become independent.\n\n"
                "Moving the copy makes the two overlap less and less, so the sum has fewer and fewer voxel pairs in it. "
                "Left alone, that alone would pull the curve down -- a small cube would look as if its speckles were "
                "smaller. Dividing every lag by the number of pairs that actually overlap, M(h), removes it exactly, and "
                "the length no longer depends on the size of the cube it was measured in."
            )
        )
        t["acf_formula"].setText(
            "g(<b>x</b>) = f(<b>x</b>) − mean(f)"
            "<br>ρ(<b>h</b>) = [ Σ g(<b>x</b>) · g(<b>x</b> + <b>h</b>) / M(<b>h</b>) ]"
            " / [ Σ g(<b>x</b>)<sup>2</sup> / M(<b>0</b>) ]"
            "<br><span style='color:#94a3b8; font-size:12px;'>M(<b>h</b>): voxel pairs at lag <b>h</b>, "
            "Π<sub>j</sub>(N<sub>j</sub> − |h<sub>j</sub>|) in a cube of N<sub>j</sub> voxels; ρ(L) = 1/e ≈ 0.37</span>"
        )
        t["acf_caption"].setText(
            self.tr(
                "The cube and its shifted copy: only the overlap (blue) contributes, and dividing by it lifts the curve "
                "back onto the true one."
            )
        )
        t["region_head"].setText(self.tr("Step 1: the region (optional)"))
        t["region_body"].setText(
            self.tr(
                "The region says where the analysis may look. It starts as the whole volume, so you can go straight to "
                "step 2; draw it, or copy the DVC region of interest, to keep the cubes out of the air around the "
                "specimen. It is not the DVC region of interest: the two never affect each other."
            )
        )
        t["rve_head"].setText(self.tr("Step 2: the representative volume element (RVE)"))
        t["rve_body"].setText(
            self.tr(
                "A small cube gives a noisy length: it sees only a few speckles. The representative volume element is "
                "the size from which the length no longer changes. Pick a centre point; cubes of growing size around it "
                "are analysed, each on its own voxels alone, and the first size of the stable run becomes step 3. Reading "
                "the curve as a convergence study is only fair because of the correction above: without it the sizes "
                "would differ for a reason that has nothing to do with the texture."
            )
        )
        t["rve_caption"].setText(
            self.tr("Cubes of growing size about one centre; the 1/e length settles once the cube is large enough.")
        )
        t["subset_head"].setText(self.tr("Step 3: from the length to the subset"))
        t["subset_body"].setText(
            self.tr(
                "A subset must span several correlation lengths on every axis, so it always holds enough texture. The "
                "suggestion is 4 times the 1/e length per axis (the factor can be changed in step 3), rounded to an odd "
                "number of voxels, with a step of half the subset. It is a recommended start, not a guarantee: a noisy "
                "scan may need a larger subset, a finely varying displacement field a smaller one. Check the run and "
                "adjust. Apply writes both into the DVC parameters."
            )
        )
        t["subset_formula"].setText(
            "subset ≈ 4 · L(1/e)   step ≈ subset / 2"
            "<br><span style='color:#94a3b8; font-size:12px;'>" + self.tr("recommended start, not a guarantee") + "</span>"
        )
        t["subset_caption"].setText(
            self.tr("The 1/e length on the texture, the subset it suggests and the step to the next subset.")
        )
