# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the portable Windows bundle of pyALDVC.

Produces a onedir tree the user unzips and runs by double-clicking
``pyALDVC.exe`` -- no installer, no Python, no admin rights. Build with
``python tools/build_exe.py`` (output under ``dist-exe/``, never ``dist/``,
which is what the PyPI workflow publishes from).

The ``al_dvc/`` prefix on every ``datas`` destination is load-bearing: a
frozen package's ``__file__`` is ``sys._MEIPASS/al_dvc/<subpkg>/...``, so the
data directories resolved with ``Path(__file__).parent`` only line up if the
destination mirrors the package path. Both data sets are asserted to exist at
build time rather than discovered missing by a user.
"""

import glob
import os

from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata

SRC = os.path.join(SPECPATH, os.pardir, "src")
PKG = os.path.join(SRC, "al_dvc")

_arrows = glob.glob(os.path.join(PKG, "gui", "arrows", "*.svg"))
assert len(_arrows) == 4, f"expected 4 spin-box arrow SVGs, found {len(_arrows)}"
_translations = glob.glob(os.path.join(PKG, "gui", "translations", "*.json"))
assert _translations, "no translation dictionaries found in al_dvc/gui/translations"

# --------------------------------------------------------------------------
# Version resource (Explorer properties)
# --------------------------------------------------------------------------
_ver_ns = {}
with open(os.path.join(PKG, "__init__.py"), encoding="utf-8") as _f:
    for _line in _f:
        if _line.startswith("__version__"):
            exec(_line, _ver_ns)
            break
VERSION = _ver_ns["__version__"]
_v = tuple(int(p) for p in VERSION.split(".")[:3]) + (0,)

VERSION_FILE = os.path.join(SPECPATH, "version_info.txt")
ICON = os.path.join(SPECPATH, os.pardir, "assets", "icon", "pyALDVC.ico")
ICON = ICON if os.path.isfile(ICON) else None
with open(VERSION_FILE, "w", encoding="utf-8") as _f:
    _f.write(f"""# Generated by pyaldvc.spec -- do not edit, do not commit.
VSVersionInfo(
  ffi=FixedFileInfo(filevers={_v}, prodvers={_v}, mask=0x3f, flags=0x0,
                    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable('040904B0', [
        StringStruct('CompanyName', 'Zixiang (Zach) Tong'),
        StringStruct('FileDescription', 'pyALDVC - Augmented Lagrangian Digital Volume Correlation'),
        StringStruct('FileVersion', '{VERSION}'),
        StringStruct('InternalName', 'pyALDVC'),
        StringStruct('LegalCopyright', 'BSD-3-Clause'),
        StringStruct('OriginalFilename', 'pyALDVC.exe'),
        StringStruct('ProductName', 'pyALDVC'),
        StringStruct('ProductVersion', '{VERSION}')])]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
""")

# --------------------------------------------------------------------------
# Bundle contents
# --------------------------------------------------------------------------
datas = [
    (os.path.join(PKG, "gui", "arrows", "*.svg"), "al_dvc/gui/arrows"),
    (os.path.join(PKG, "gui", "translations", "*.json"), "al_dvc/gui/translations"),
    (os.path.join(PKG, "gui", "assets", "*"), "al_dvc/gui/assets"),
]
for _dist in ("numba", "llvmlite", "tifffile", "h5py"):
    try:
        datas += copy_metadata(_dist)
    except Exception:  # metadata missing -> the import guard in the package decides
        pass

hiddenimports = [
    # compiled helpers numba imports lazily (numba/__init__ pulls them in through numba.misc / numba.core);
    # without them the frozen app raises ImportError on "import numba" and every kernel falls back to NumPy
    "numba._devicearray",
    "numba.mviewbuf",
    # QSS references SVG arrows; without the SVG image plugin the spin boxes lose their arrows silently.
    "PySide6.QtSvg",
    # Numba's threading layers are imported by name inside functions.
    "numba.np.ufunc.omppool",
    "numba.np.ufunc.workqueue",
    "numba.np.ufunc._internal",
    "numba.np.ufunc._num_threads",
    # The slice viewer embeds a matplotlib canvas; reports use Agg and the PDF backend.
    "matplotlib.backends.backend_qtagg",
    "matplotlib.backends.backend_agg",
    "matplotlib.backends.backend_pdf",
    # 3-D view: pyvista, pyvistaqt and the VTK modules they import (see _vtk_modules_in_use below).
    "vtkmodules.qt.QVTKRenderWindowInteractor",
    # Volume readers selected by file extension at runtime.
    "tifffile",
    "h5py",
    "yaml",
    "scipy.io",
    "scipy.io.matlab",
    "scipy.ndimage",
    "scipy.sparse.linalg",
    "scipy.fft",
]



def _vtk_modules_in_use():
    """VTK / pyvista modules loaded by importing pyvista, pyvistaqt and rendering one scene.

    pyvista imports most ``vtkmodules.*`` lazily, so a static analysis collects
    only a handful and the frozen import fails; collecting every VTK module
    would add hundreds of MB. Importing the real thing in the build
    environment gives the exact list for the installed versions.
    """
    import subprocess
    import sys

    probe = (
        "import sys, json; import pyvista as pv; import pyvistaqt; "
        "pv.OFF_SCREEN = True; pl = pv.Plotter(off_screen=True, window_size=(64, 48)); "
        "g = pv.ImageData(dimensions=(3, 3, 3)); import numpy as np; g.point_data['f'] = np.arange(27.0); "
        "pl.add_mesh(g.slice_orthogonal(), scalars='f'); pl.add_mesh(g.outline()); pl.add_mesh(g.contour([13.0])); "
        "pl.add_mesh(g.warp_by_vector() if 'v' in g.point_data else g); "
        "c = pv.PolyData(np.zeros((2, 3))); c['vec'] = np.ones((2, 3)); c['mag'] = np.ones(2); "
        "pl.add_mesh(c.glyph(orient='vec', scale='mag', factor=1.0)); pl.add_scalar_bar(title='f'); pl.add_axes(); "
        "pl.view_isometric(); pl.screenshot(None, return_img=True); pl.close(); "
        "print(json.dumps(sorted(m for m in sys.modules if m.startswith(('vtkmodules', 'pyvista', 'pyvistaqt', 'scooby', 'pooch')))))"
    )
    out = subprocess.run([sys.executable, "-c", probe], capture_output=True, text=True, check=True, timeout=600)
    import json

    modules = json.loads(out.stdout.strip().splitlines()[-1])
    assert any(m.startswith("vtkmodules.vtkRendering") for m in modules), "probe did not load VTK rendering modules"
    return modules


try:
    _view3d_modules = _vtk_modules_in_use()
    hiddenimports += _view3d_modules
    hiddenimports += [m for m in collect_submodules("pyvistaqt")]
    datas += collect_data_files("pyvista", excludes=["**/*.py", "**/examples/**"])
    datas += collect_data_files("pyvistaqt", excludes=["**/*.py"])
    print(f"pyaldvc.spec: 3-D view -> {len(_view3d_modules)} pyvista/VTK modules collected")
except Exception as _exc:  # no pyvista in the build environment: the tab shows the install hint
    print(f"pyaldvc.spec: 3-D view not bundled ({_exc})")

binaries = []
# The OpenMP runtime behind numba's 'omp' threading layer (app-local deployment is
# permitted by the VC++ redistributable licence); without it numba silently falls
# back to 'workqueue'.
_vcomp = os.path.join(os.environ.get("SystemRoot", r"C:\Windows"), "System32", "vcomp140.dll")
if os.path.isfile(_vcomp):
    binaries.append((_vcomp, "."))

excludes = [
    "PySide6.Qt3DAnimation", "PySide6.Qt3DCore", "PySide6.Qt3DExtras", "PySide6.Qt3DInput", "PySide6.Qt3DLogic",
    "PySide6.Qt3DRender", "PySide6.QtAxContainer", "PySide6.QtBluetooth", "PySide6.QtCharts", "PySide6.QtConcurrent",
    "PySide6.QtDataVisualization", "PySide6.QtDBus", "PySide6.QtDesigner", "PySide6.QtGraphs", "PySide6.QtGraphsWidgets",
    "PySide6.QtHelp", "PySide6.QtHttpServer", "PySide6.QtLocation", "PySide6.QtMultimedia", "PySide6.QtMultimediaWidgets",
    "PySide6.QtNetworkAuth", "PySide6.QtNfc", "PySide6.QtPdf",
    "PySide6.QtPdfWidgets", "PySide6.QtPositioning", "PySide6.QtQml", "PySide6.QtQuick", "PySide6.QtQuick3D",
    "PySide6.QtQuickControls2", "PySide6.QtQuickTest", "PySide6.QtQuickWidgets", "PySide6.QtRemoteObjects",
    "PySide6.QtScxml", "PySide6.QtSensors", "PySide6.QtSerialBus", "PySide6.QtSerialPort", "PySide6.QtSpatialAudio",
    "PySide6.QtSql", "PySide6.QtStateMachine", "PySide6.QtSvgWidgets", "PySide6.QtTest", "PySide6.QtTextToSpeech",
    "PySide6.QtUiTools", "PySide6.QtWebChannel", "PySide6.QtWebEngineCore", "PySide6.QtWebEngineQuick",
    "PySide6.QtWebEngineWidgets", "PySide6.QtWebSockets", "PySide6.QtWebView", "PySide6.QtXml", "PySide6.QtNetwork",
    # rival Qt bindings must never co-exist in one bundle
    "PyQt5", "PyQt6", "PySide2", "shiboken2",
    # unused matplotlib backends
    "matplotlib.backends.backend_qtcairo", "matplotlib.backends.backend_webagg", "matplotlib.backends.backend_tkagg",
    # a desktop application that reads volumes off a disk: no TLS stack
    "ssl", "_ssl",
    # numba threading layers other than omp/workqueue (tbb is not installed; its pool would only add a warning)
    "numba.np.ufunc.tbbpool",
    # the "vtk" facade imports every VTK module (hundreds of MB); pyvista uses vtkmodules directly
    "vtk",
    # the CUDA backend is a pip extra (numba-cuda + CUDA 12 wheels, driver-specific): the bundle stays CPU-only
    "numba_cuda", "numba.cuda", "cuda", "cuda_bindings", "cuda_core", "cuda_pathfinder", "cuda_toolkit", "nvidia",
    # optional heavy extras
    "IPython", "jupyter", "notebook", "tkinter",
]

a = Analysis(
    [os.path.join(SPECPATH, "pyaldvc_launcher.py")],
    pathex=[SRC],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[os.path.join(SPECPATH, "rthook_pyaldvc.py")],
    excludes=excludes,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="pyALDVC",
    icon=ICON,
    debug=False,
    strip=False,
    upx=False,
    console=False,
    version=VERSION_FILE,
)
exe_console = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="pyALDVC-console",
    icon=ICON,
    debug=False,
    strip=False,
    upx=False,
    console=True,
    version=VERSION_FILE,
)
coll = COLLECT(
    exe,
    exe_console,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    name="pyALDVC",
)
